### PR TITLE
use circle ci

### PR DESCRIPTION
**Pull request by macool**

### CODE REVIEW

**Comment by macool** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EN78BdMz&#x2F;442-move-apps-to-circleci"> Move Apps to circleCI</a>

**Comment by rusllonrails** [comment]
@macool looks fine.

1) would be good to add Circle CI widget into README
```
[![Circle CI](https://circleci.com/gh/bitzesty/trade-tariff-backend.svg?style=svg)](https://circleci.com/gh/bitzesty/trade-tariff-backend)
```
2) I see more stuff in .travis.yml
https://github.com/bitzesty/trade-tariff-admin/blob/master/.travis.yml#L6

```
before_script:
   - mysql -e 'CREATE DATABASE tariff_admin_test;'
before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq wbritish
   - cp config/database.travis.yml config/database.yml
script:
 - RAILS_ENV=test bundle exec rake bundler:audit
 - RAILS_ENV=test bundle exec rake db:create
 - RAILS_ENV=test bundle exec rake db:migrate
 - RAILS_ENV=test bundle exec rake spec
```

but new circle.yml looks much simpler (if compare with .travis.yml):
```
dependencies:
  bundler:
    without: [development]
  post:
    - bundle exec rake bundler:audit
```
Probably we missing smth in circle.yml. Does it?

3) Do we still need .travis.yml?

**Comment by matthewford** [comment]
@macool can we do this against CF instead?

**Comment by macool** [comment]
using #10

**Pull request closed without merging**
